services:

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile

    container_name: keystroke_backend

    ports:
      - "10000:10000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile

    container_name: keystroke_frontend

    ports:
      - "8501:8501"

    depends_on:
      - backend